"""Initial migration after removing CPF from Doacao

Revision ID: 828a74884193
Revises: 
Create Date: 2025-06-17 10:46:08.325510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828a74884193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doacoes', schema=None) as batch_op:
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
